force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>Used to track work done by employees</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>W-{0000000}</displayFormat>
        <label>Work Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Difficulty__c</fullName>
    <label>Difficulty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Estimated_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_End_Date__c</fullName>
    <label>Estimated End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;New&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkItemKanbanController.cls
public with sharing class WorkItemKanbanController {
    @AuraEnabled
    public static List<Work_Item__c> getWorkItems() {
        if (Schema.sObjectType.Work_Item__c.isAccessible()) {
            return [SELECT Id, Title__c, Difficulty__c, Status__c, Start_Date__c, Estimated_End_Date__c, RecordTypeId, RecordType.Name FROM Work_Item__c WHERE Start_Date__c >= LAST_N_DAYS:30];
        }
        else {
            return NULL;
        }
    }
    @AuraEnabled
    public static Boolean itemIsOverdue(Work_Item__c workItem) {
        if(workItem.Estimated_End_Date__c <= Date.today()){
            return TRUE;
        }
        else{
            return FALSE;
        }
    }
    
    @AuraEnabled
    public static void updateStatus(Work_Item__c workItem, String status) {
        try {
            if (Schema.sObjectType.Work_Item__c.fields.Status__c.isUpdateable()){
                workItem.Status__c = status;
                update workItem; 
            } 
        } catch(DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
    }

    @AuraEnabled
    public static List<String> getPicklistValues() {
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = Work_Item__c.Status__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : picklistValues){
	        pickListValuesList.add(pickListVal.getLabel());
        }
        return pickListValuesList;
    }
}