force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>Used to track work done by employees</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>W-{0000000}</displayFormat>
        <label>Work Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Difficulty__c</fullName>
    <label>Difficulty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Estimated_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_End_Date__c</fullName>
    <label>Estimated End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;New&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkItemKanbanTest.cls
@isTest
private class WorkItemKanbanTest {
    @testSetup static void setup() {
        List<Work_Item__c> workItemsList = new List<Work_Item__c>();
        Work_Item__c workItem1 = new Work_Item__c(Title__c = 'Work Item 1', Start_Date__c = Date.today().addDays(-10), Status__c = 'New', Estimated_End_Date__c = Date.today().addDays(-2));
        Work_Item__c workItem2 = new Work_Item__c(Title__c = 'Work Item 2', Start_Date__c = Date.today().addDays(-10), Status__c = 'New', Estimated_End_Date__c = Date.today().addDays(2));
        workItemsList.add(workItem1);
        workItemsList.add(workItem2);
        insert workItemsList;
    }

    @isTest
    public static void testGetItems() {
        test.startTest();

        List<Work_Item__c> workItemsList = [SELECT Id, Title__c, Difficulty__c, Status__c, Start_Date__c, Estimated_End_Date__c, RecordTypeId, RecordType.Name FROM Work_Item__c WHERE Start_Date__c >= LAST_N_DAYS:30]; 
        
        Test.stopTest();

        System.assertEquals(workItemsList.size(),(WorkItemKanbanController.getWorkItems()).size(), 'No work items found');
    }

    @isTest
    public static void testIsOverdue(){
        test.startTest();

        Work_Item__c workItem1 = [SELECT Id, Title__c, Difficulty__c, Status__c, Start_Date__c, Estimated_End_Date__c FROM Work_Item__c WHERE Title__c = 'Work Item 1' LIMIT 1];
        Work_Item__c workItem2 = [SELECT Id, Title__c, Difficulty__c, Status__c, Start_Date__c, Estimated_End_Date__c FROM Work_Item__c WHERE Title__c = 'Work Item 2' LIMIT 1];
    
        Test.stopTest();

        System.assertEquals(WorkItemKanbanController.itemIsOverdue(workItem1), TRUE, 'Result is not true');
        System.assertEquals(WorkItemKanbanController.itemIsOverdue(workItem2), FALSE, 'Result is not false');
    }

    @isTest
    public static void testUpdateStatus() {
        test.startTest();

        Work_Item__c workItem1 = [SELECT Id, Title__c, Difficulty__c, Status__c, Start_Date__c FROM Work_Item__c WHERE Title__c = 'Work Item 1' LIMIT 1]; 
        Work_Item__c workItem2 = [SELECT Id, Title__c, Difficulty__c, Status__c, Start_Date__c FROM Work_Item__c WHERE Title__c = 'Work Item 2' LIMIT 1]; 
        WorkItemKanbanController.updateStatus(workItem1, 'Done');
        WorkItemKanbanController.updateStatus(workItem2, 'Bad Value');

        Test.stopTest();

        System.assertEquals(workItem1.Status__c,'Done', 'Status does not match');
    }
}