force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>Used to track work done by employees</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>W-{0000000}</displayFormat>
        <label>Work Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Assigned_to__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned to</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;New&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkItemViewControllerTest.cls
@isTest
private class WorkItemViewControllerTest {
    @testSetup static void setup() {
        Contact contact = new Contact (Lastname = 'Test');
        insert contact;

        List<Work_Item__c> workItemsList = new List<Work_Item__c>();
        Work_Item__c workItem1 = new Work_Item__c(Title__c = 'Work Item 1', Status__c = 'New', Assigned_to__c = contact.Id);
        Work_Item__c workItem2 = new Work_Item__c(Title__c = 'Work Item 2', Status__c = 'New', Assigned_to__c = contact.Id);
        workItemsList.add(workItem1);
        workItemsList.add(workItem2);
        insert workItemsList;
    }

    @isTest
    public static void testGetWorkItems(){
        test.startTest();

        Contact contact = [SELECT Id FROM Contact WHERE Lastname = 'Test' LIMIT 1];
        List<Work_Item__c> workItemList = [SELECT Id FROM Work_Item__c WHERE Assigned_to__c = :contact.Id];

        Test.stopTest();

        System.assertEquals((WorkItemViewController.getWorkItems(contact.Id)).size(), workItemList.size(),'Size does not match');
    }

    @isTest
    public static void testDeleteWorkItems(){

        test.startTest();

        Contact contact = [SELECT Id FROM Contact WHERE Lastname = 'Test' LIMIT 1];
        Work_Item__c workItemDelete = [SELECT Id FROM Work_Item__c WHERE Title__c = 'Work Item 2' LIMIT 1];
        WorkItemViewController.deleteWorkItem(workItemDelete.Id);

        Test.stopTest();

        System.assertEquals((WorkItemViewController.getWorkItems(contact.Id)).size(), 1, 'Item was not deleted');
    }
}