force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>Used to track work done by employees</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>W-{0000000}</displayFormat>
        <label>Work Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Estimated_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_End_Date__c</fullName>
    <label>Estimated End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;New&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkItemOverdueScheduleTest.cls
@isTest
private class WorkItemOverdueScheduleTest {
    @testSetup static void setup() {
        List<Work_Item__c> workItemsList = new List<Work_Item__c>();
        Work_Item__c workItem1 = new Work_Item__c(Estimated_End_Date__c = Date.today().addDays(-1), Status__c = 'New');
        Work_Item__c workItem2 = new Work_Item__c(Estimated_End_Date__c = Date.today().addDays(-2), Status__c = 'New');
        workItemsList.add(workItem1);
        workItemsList.add(workItem2);
        insert workItemsList;
    }

    @isTest
    public static void testGetAdmins() {
        test.startTest();

        String sysAdmin = 'System Administrator';
        List<User> adminUsers = [SELECT Id, Email FROM User WHERE Profile.Name = :sysAdmin];
        List<String> adminEmails = new List<String>();
        for(User admin : adminUsers){
            adminEmails.add(admin.Email);
        }

        Test.stopTest();

        System.assertEquals(adminEmails.size(),(WorkItemOverdueSchedule.getAdminEmails()).size(),'No admin users found');
    }

    @isTest
    public static void testGetWorkItems(){
        test.startTest();

        String status = 'Done';
        List<Work_Item__c> workItemsList = [SELECT Id, Name, Title__c, Estimated_End_Date__c, Status__c FROM Work_Item__c WHERE Estimated_End_Date__c <= TODAY AND Status__c != :status]; 
        
        Test.stopTest();

        System.assertEquals(workItemsList.size(),(WorkItemOverdueSchedule.getOverdueItems()).size(), 'No work items found');
    }

    @isTest
    public static void testSchedule(){
        
        String CRON_EXP = '0 0 0 15 3 ? *';

        test.startTest();

		String jobId = System.schedule('ScheduleApexClassTest',  CRON_EXP, new WorkItemOverdueSchedule());
		CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
		
        test.stopTest();
        
        System.assertEquals(CRON_EXP, ct.CronExpression, 'Error on schedule context');
		System.assertEquals(0, ct.TimesTriggered, 'Error getting schedule info');
    }
}