force-app/main/default/objects/Work_Item__c/Work_Item__c.object-meta.xml
<CustomObject>
    <description>Used to track work done by employees</description>
    <label>Work Item</label>
    <nameField>
        <displayFormat>W-{0000000}</displayFormat>
        <label>Work Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Item__c/fields/Assigned_to__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned to</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Work Items</relationshipLabel>
    <relationshipName>Work_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Difficulty__c</fullName>
    <label>Difficulty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Estimated_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_End_Date__c</fullName>
    <label>Estimated End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;New&quot;)</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WorkItemViewController.cls
public with sharing class WorkItemViewController {
    @AuraEnabled
    public static List<Work_Item__c> getWorkItems(Id contactId) {
        if (Schema.sObjectType.Work_Item__c.isAccessible()) {
            return [SELECT Id, Name, Title__c, Difficulty__c, Status__c, Start_Date__c, Estimated_End_Date__c, End_Date__c, RecordTypeId, RecordType.Name FROM Work_Item__c WHERE Assigned_to__c = :contactId];
        }
        else {
            return NULL;
        }
    }

    @AuraEnabled
    public static void deleteWorkItem(Id itemId) {
        if (Schema.sObjectType.Work_Item__c.isDeletable()) {
            Work_Item__c workItem = [SELECT Id FROM Work_Item__c WHERE Id = :itemId LIMIT 1];
            delete workItem;
        }
    }
}